tarp_detection:
  ros__parameters:

    # ── Topics ────────────────────────────────────────────────────────────────
    image_topic:       "/camera_feed"
    global_pos_topic:  "/fmu/out/vehicle_global_position"
    local_pos_topic:   "/fmu/out/vehicle_local_position"

    # ── Target colour (BGR order) ─────────────────────────────────────────────
    # Red:    [0, 0, 255]
    # Blue:   [255, 0, 0]
    # Orange: [0, 140, 255]
    target_color_bgr: [151, 82, 2] # This is the color blue from thte sample image I am using for SITL testing. This would be changed
                                   # when we receive our actual tarp so we can test for reals with it

    # ── Colour matching ───────────────────────────────────────────────────────
    color_tolerance: 50     # HSV distance — raise if missing detections,
                            # lower if too many false positives
    min_pixels: 500         # ignore blobs smaller than this
    max_pixels: 200000      # ignore blobs larger than this

    # ── Camera geometry — adjust to match your lens ───────────────────────────
    camera_hfov_deg: 84.0
    camera_vfov_deg: 54.0
